### ISSUE TITLE
Misleading documentation about connection strings an unix sockets

### ISSUE THREAD

**Issue by adamvandenhovenfm** [npgsql/doc#1]
If you look on the [page related to connection string parameters](http://www.npgsql.org/doc/connection-string-parameters.html?q=Unix-domain%20sockets) you will see that of the `Host` parameter it says "If the value begins with a slash, it is used as the directory for the Unix-domain socket." This implies, at least to me, that npgsql can connect over Unix socket (and indeed I've spent much of the last hour trying to do just that) however if you go the  [security page](http://www.npgsql.org/doc/security.html?q=Unix-domain%20sockets) we find that in fact "Npgsql does not support logging in via Unix-domain sockets (auth method local)."

The connection string page needs to be _much_ clearer about this than it currently is. I would also like to see a link to the security page. I would also suggest adding to the description of the username and password parameters not that makes it clear that the pg_hba.conf needs to be configured to allow _that_ user to connect to _that_ database using `password` or `md5`. It should also be made clear that the it is not necessary to change your password parameter if the method is set to md5 (unless it is, in which case you should let us know that fact and how to change the password accordingly).

**Comment by roji** [comment]
You're right that there's a discrepancy in the docs - Npgsql *does* support connecting with Unix-domain sockets (#1388), I've updated the security page to indicate that.

Regarding your second comment, I don't think educating users about pg_hba.conf should be a goal of the Npgsql docs - these are purely PostgreSQL-side configuration details. I haven't received any complaints from users who didn't know about pg_hba.conf, or thought that using method `md5` requires any change to the password parameter (and the security page does clearly say that "Npgsql will send the password in MD5 or in cleartext (not recommended)".

Let me know if you run into any difficulties with Unix-domain sockets or otherwise.
