### ISSUE TITLE
Prepare Documentation Needs Improvement

### ISSUE THREAD

**Issue by pha3z** [npgsql/doc#91]
https://www.npgsql.org/doc/prepare.html shows an example of two UPDATE statements. It explains that the individual statements are prepared. However, it doesn't clearly state if using multiple statements with a single prepare in one command is actually the best practice.

What if I want to do 200 Updates or 200 Inserts? Do I put all 200 Updates in a single parameterized query and call Prepare() once followed by ExecuteQuery()? Is this the optimal way to do it? 

Would it perform differently if I created 1 single Update statement in one query, prepared it, executed.... and then put the remaining 199 in a second query without preparing it? I feel like it would help if the documentation explained better what's happening under the hood.

Another example on the same page demonstrates Preparing a query, Executing it, then changing the parameters and Executing it again. Is this meant to be in a loop?? The code is lacking explanation. 

**Maybe some guidance on how to use prepare based on what KIND of operation(s) you're doing would be helpful.**

**Comment by roji** [comment]
> What if I want to do 200 Updates or 200 Inserts? Do I put all 200 Updates in a single parameterized query and call Prepare() once followed by ExecuteQuery()? Is this the optimal way to do it?

Probably. As the docs state (pretty clearly):

> Note that preparation happens on individual statements, and not on commands, which can contain multiple statements, batching them together. [...] Although there are two statements in this command, the same prepared statement is used to execute since the SQL is identical.

So batching 200 Updates/Inserts via a single NpgsqlCommand will perform all of them in a single round-trip (that's the batching part), and also reuse the same PostgreSQL prepared statement (assume the statements are identical except for the parameter values). It seems to me that this is already described in the text.

> Would it perform differently if I created 1 single Update statement in one query, prepared it, executed.... and then put the remaining 199 in a second query without preparing it? I feel like it would help if the documentation explained better what's happening under the hood.

If automatic preparation isn't on, then your second query would run unprepared, which is sub-optimal. There's no advantage AFAIK in splitting a execution into two commands rather than one - you're just adding an additional database roundtrip for no reason.

> Another example on the same page demonstrates Preparing a query, Executing it, then changing the parameters and Executing it again. Is this meant to be in a loop?? The code is lacking explanation.

I'm assuming you're referring to the code sample in the [persistency section](https://www.npgsql.org/doc/prepare.html#persistency). That code shows that prepared statements persist across different (pooled) connections.

**Comment by pha3z** [comment]
So what you're telling me is:

It's irrelevant how many statements appear inside of a Query. Also, whether or not they are the same repeated statement or a mix of different statements is irrelevant. Prepare() will automatically discern how to prepare all of the individual statements in the most optimal way.

**Comment by roji** [comment]
> It's irrelevant how many statements appear inside of a Query

Pretty much. A command execution corresponds to a database roundtrip; perf-wise, more commands just mean more roundtrips, so AFAIK it's almost always better to batch more statements into a single command rather than splitting statements into multiple commands.

> Also, whether or not they are the same repeated statement or a mix of different statements is irrelevant. Prepare() will automatically discern how to prepare all of the individual statements in the most optimal way.

Pretty much. Both explicit Prepare() and automatic preparation maintain an internal SQL cache, and when a new statement is seen, they will check if it has already been prepared. This happens regardless of whether the statements are batched in a single command or split across different commands.

**Comment by pha3z** [comment]
This clears up any concerns I had.  I still feel like the linked doc page doesn't instill a lot of confidence.  Your confirmation to my statements removed any doubts about how it might work.

**Comment by pha3z** [comment]
Also, thank you!!!  I really appreciate it !
